# Don't print a new line at the start of the prompt
#add_newline = false

# Replace the "?" symbol in the prompt with "?"
[character]      # The name of the module we are confguring is "character"
symbol = ">"     # The "symbol" segment is being set to "?"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Overwrite a default_prompt_order and  use custom prompt_order
# prompt_order=["rust","line_break","package","line_break","character"]

[hostname]
ssh_only = false
prefix = "<<"
suffix = ">>"
disabled = true

[line_break]
disabled = true

[username]
# disabled = true
style_root = "bold red"
style_user = "bold yellow"

[cmd_duration]
disabled = true
